- env_id: Endless-v0
  env_configs:
    carla_map_train: Town01
    carla_map_val: Town02
    num_zombie_vehicles: [0, 100]
    num_zombie_walkers: [0, 200]
    weather_group_train: train
    weather_group_val: new
    carla_fps: 10
    reward:
      entry_point: reward.valeo_action_updated:ValeoAction
      kwargs : 
        maximum_speed: 5
    terminal: 
      entry_point: terminal.valeo_no_det_px:ValeoNoDetPx
      kwargs : {}
